# Use new trusty images, should yield newer compilers and packages
sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - compiler: g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libopencv-dev
    - compiler: g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libopencv-dev
    - compiler: clang++-3.4
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.4
          packages:
            - clang++-3.4
            - libopencv-dev
    - compiler: clang++
      addons:
        apt:
          packages:
            -libopencv-dev
script:
  - $CXX --version
  - ls /usr/share/OpenCV
  - ls /usr/lib | grep -i opencv
  - mkdir build
  - cd build
  - cmake .. && make -j$(nproc --all)
  - ./dkm_tests
  - ./dkm_bench
  