# Use new trusty images, should yield newer compilers and packages
sudo: false
dist: trusty
language: cpp

matrix:
  include:
    - compiler: g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libopencv-dev
      env: 
        - C_COMPILER=gcc-4.9
        - CXX_COMPILER=g++-4.9
    - compiler: g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - libopencv-dev
      env: 
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
    - compiler: clang++-3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.5
            - clang++-3.5
            - gcc-4.9
            - g++-4.9
            - libopencv-dev
      env: 
        - C_COMPILER=clang-3.5
        - CXX_COMPILER=clang++-3.5
    - compiler: clang++-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - clang++-5.0
            - gcc-4.9
            - g++-4.9
            - libopencv-dev
      env: 
        - C_COMPILER=clang-5.0
        - CXX_COMPILER=clang++-5.0
script:
  - $CXX_COMPILER --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j$(nproc --all)
  - ./dkm_tests
  - ./dkm_bench
  