# This is a basic workflow to help you get started with Actions

name: dkm-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx: [clang++, g++]
        include:
          - cxx: clang++
            cc: clang
          - cxx: g++
            cc: gcc
    steps:
      - name: Install dependencies
        run: sudo apt-get install libopencv-dev
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Create build directory
        run: mkdir build
      - name: Build DKM
        working-directory: build
        run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DCMAKE_C_COMPILER=${{ matrix.cc }} -DDKM_WARNINGS_AS_ERRORS=ON .. && cmake --build .
      - name: Run tests
        working-directory: build
        run: ./dkm_tests
      - name: Run benchmarks
        working-directory: build
        run: ./dkm_bench

  build-and-test-windows:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: choco install opencv
      - name: Set OpenCV path
        run: echo "C:\tools\opencv\build\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Create build directory
        run: mkdir build
      - name: Build DKM
        working-directory: build
        run: cmake -DDKM_WARNINGS_AS_ERRORS=ON -DOpenCV_DIR="C:\tools\opencv\build" .. && cmake --build . --config Release
      - name: Run tests
        working-directory: build/Release
        run: .\dkm_tests.exe
      - name: Run benchmarks
        working-directory: build/Release
        run: .\dkm_bench.exe
